### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 79-85: ordinal not in range(256)

### ISSUE THREAD

**Issue by yhbas** [CoderWanFeng/popdf#3]
files amount:1
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "d:\work\PythonProjects\小说拆分\小说按字数自动拆分.py", line 77, in <module>
    office.pdf.txt2pdf(path=fo_name, res_pdf="txt2pdf.popdf", output_path=fdir1)
  File "C:\Users\13154\AppData\Roaming\Python\Python311\site-packages\office\api\pdf.py", line 57, in txt2pdf
    popdf.txt2pdf(path, res_pdf, output_path)
  File "C:\Users\13154\AppData\Roaming\Python\Python311\site-packages\popdf\api\pdf.py", line 26, in txt2pdf
    mainPDF.txt2pdf(path, res_pdf, output_path)
  File "C:\Users\13154\AppData\Roaming\Python\Python311\site-packages\popdf\core\PDFType.py", line 74, in txt2pdf
    pdf.output(os.path.join(abs_output_path, res_pdf))
  File "C:\Users\13154\AppData\Roaming\Python\Python311\site-packages\fpdf\fpdf.py", line 1065, in output
    self.close()
  File "C:\Users\13154\AppData\Roaming\Python\Python311\site-packages\fpdf\fpdf.py", line 246, in close  
    self._enddoc()
  File "C:\Users\13154\AppData\Roaming\Python\Python311\site-packages\fpdf\fpdf.py", line 1636, in _enddoc
    self._putpages()
  File "C:\Users\13154\AppData\Roaming\Python\Python311\site-packages\fpdf\fpdf.py", line 1170, in _putpages
    p = self.pages[n].encode("latin1") if PY3K else self.pages[n]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 79-85: ordinal not in range(256)

**Comment by CoderWanFeng** [comment]
pip install pymupdf popdf -U
